Update to Scala 2.12.18
In this update, I also had to update akka because of a dependency
conflict:

java.lang.RuntimeException: found version conflict(s) in library dependencies; some are suspected to be binary incompatible:

* org.scala-lang.modules:scala-xml_2.12:2.1.0 (early-semver) is selected over {1.1.1}
   +- org.scala-lang:scala-compiler:2.12.18              (depends on 2.1.0)
   +- com.typesafe.akka:akka-http-xml_2.12:10.1.8        (depends on 1.1.1)