Declare Location to be Seralizable since used in ParseException and sbt test seems to complain about broken pipes:
Reporter completed abruptly with an exception after receiving event: TestSucceeded(Ordinal(0, 72),ProvabilityExamples,ProvabilityExamples,Some(ProvabilityExamples),The Default Tactic should handle obvious proofs,should handle obvious proofs,Vector(),Some(45),Some(IndentedText(- should handle obvious proofs,should handle obvious proofs,1)),Some(LineInFile(35,ProvabilityExamples.scala)),Some(ProvabilityExamples),None,pool-1-thread-1-ScalaTest-running-ProvabilityExamples,1436320198721).
java.net.SocketException: Broken pipe
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
	at java.io.ObjectOutputStream$BlockDataOutputStream.drain(ObjectOutputStream.java:1877)
	at java.io.ObjectOutputStream$BlockDataOutputStream.writeByte(ObjectOutputStream.java:1915)
	at java.io.ObjectOutputStream.writeFatalException(ObjectOutputStream.java:1576)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:351)
	at org.scalatest.tools.SocketReporter.apply(SocketReporter.scala:31)